name: Deploy web files to R2 buckets

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/CODEOWNERS'
      - '.github/workflows/cla.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: r2-deploy
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Load secret
      id: op-load-secret
      uses: 1password/load-secrets-action@v2
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        R2_ACCESS_KEY_ID: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/vsktfcerr4lzwelblqsdzio5ku
        R2_SECRET_ACCESS_KEY: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/ddid5yjvyyzobwvxghauuxs4vu
        R2_ENDPOINT: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/cwrkc6c564ds47q3ofajxgzkaa

    - name: Install Rclone
      run: |
        sudo -v ; curl https://rclone.org/install.sh | sudo bash
        rclone version
        
    - name: Setup Rclone Config
      run: |
        rclone config create r2-deploy s3 \
          provider=Cloudflare \
          access_key_id=${{ steps.op-load-secret.outputs.R2_ACCESS_KEY_ID }} \
          secret_access_key=${{ steps.op-load-secret.outputs.R2_SECRET_ACCESS_KEY }} \
          endpoint=${{ steps.op-load-secret.outputs.R2_ENDPOINT }} \
          no_check_bucket=true
        rclone listremotes
        
    - name: Deploy All Buckets
      run: |
        echo "🔍 Discovering buckets to deploy..."
        
        for folder in */; do
          if [ -f "${folder}.bucket" ]; then
            BUCKET_NAME=$(cat "${folder}.bucket" | tr -d ' \t\n\r')
            folder_name=${folder%/}  # Remove trailing slash for cleaner output
            
            echo "📦 Deploying ${folder_name} to bucket: $BUCKET_NAME"
            
            if [ "$folder" = "central/" ]; then
              echo "  └── Uploading all central resources..."
              rclone copy "$folder" r2-deploy:$BUCKET_NAME/central --exclude "*.bucket" -v
            else
              echo "  └── Uploading index.html..."
              rclone copy "${folder}index.html" r2-deploy:$BUCKET_NAME -v
            fi
            echo "  ✅ ${folder_name} deployment complete"
            echo ""
          else
            folder_name=${folder%/}
            echo "⏭️  Skipping ${folder_name} (no .bucket file found)"
          fi
        done
        
        echo "🎉 All bucket deployments complete!" 