name: Deploy metadata files to R2 buckets

on:
  push:
    branches: [ main ]
    paths:
      - '*/metadata/*.uri'
      - '*/metadata/*.md5'
      - '.github/workflows/deploy-metadata.yml'
  workflow_dispatch:

jobs:
  deploy-metadata:
    runs-on: ubuntu-latest
    environment: production-metadata

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load R2 secrets from 1Password
        id: op-load-secret
        uses: 1password/load-secrets-action@v3
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          R2_ACCESS_KEY_ID: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/vsktfcerr4lzwelblqsdzio5ku
          R2_SECRET_ACCESS_KEY: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/ddid5yjvyyzobwvxghauuxs4vu
          R2_ENDPOINT: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/cwrkc6c564ds47q3ofajxgzkaa

      - name: Install rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Setup rclone config
        run: |
          rclone config create r2-deploy s3 \
            provider=Cloudflare \
            access_key_id="${{ steps.op-load-secret.outputs.R2_ACCESS_KEY_ID }}" \
            secret_access_key="${{ steps.op-load-secret.outputs.R2_SECRET_ACCESS_KEY }}" \
            endpoint="${{ steps.op-load-secret.outputs.R2_ENDPOINT }}" \
            no_check_bucket=true --non-interactive
          rclone listremotes

      - name: Deploy metadata files
        run: |
          echo "🚀 Deploying metadata files to R2 buckets..."
          deployed_count=0
          for folder in */; do
            # Need manifest.json and metadata directory
            if [ -f "${folder}manifest.json" ] && [ -d "${folder}metadata" ]; then
              BUCKET_NAME=$(jq -r '.bucket' "${folder}manifest.json")
              if [ -z "$BUCKET_NAME" ] || [ "$BUCKET_NAME" = "null" ]; then
                echo "::error::Bucket name missing in ${folder}manifest.json. Skipping.";
                continue;
              fi
              folder_name=${folder%/}

              echo "📦 Processing ${folder_name} -> bucket ${BUCKET_NAME}"

              # Copy metadata files
              rclone copy "${folder}metadata/" "r2-deploy:${BUCKET_NAME}/metadata" --header-upload "Content-Type: text/plain; charset=utf-8" -v

              echo "  ✅ Uploaded metadata for ${folder_name}"
              deployed_count=$((deployed_count + 1))
            fi
          done

          echo "🎉 Metadata deployment complete. Deployed $deployed_count dataset(s)." 