name: Deploy web files to production

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/CODEOWNERS'
      - '.github/workflows/cla.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production-web
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Load secret
      id: op-load-secret
      uses: 1password/load-secrets-action@v3
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        R2_ACCESS_KEY_ID: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/vsktfcerr4lzwelblqsdzio5ku
        R2_SECRET_ACCESS_KEY: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/ddid5yjvyyzobwvxghauuxs4vu
        R2_ENDPOINT: op://mqgmk3badhri6yvwi3qknilwz4/hjinzlouv5hekttyckgij4iyqq/f6gocg2smekpszwxqpnn7x6jga/cwrkc6c564ds47q3ofajxgzkaa

    - name: Install Rclone
      run: |
        sudo -v ; curl https://rclone.org/install.sh | sudo bash
        rclone version
        
    - name: Setup Rclone Config
      run: |
        rclone config create r2-deploy s3 \
          provider=Cloudflare \
          access_key_id=${{ steps.op-load-secret.outputs.R2_ACCESS_KEY_ID }} \
          secret_access_key=${{ steps.op-load-secret.outputs.R2_SECRET_ACCESS_KEY }} \
          endpoint=${{ steps.op-load-secret.outputs.R2_ENDPOINT }} \
          no_check_bucket=true
        rclone listremotes
        
    - name: Deploy All Buckets
      run: |
        echo "🔍 Discovering buckets to deploy..."
        
        for folder in */; do
          if [ -f "${folder}manifest.json" ]; then
            BUCKET_NAME=$(jq -r '.bucket' "${folder}manifest.json")
            if [ -z "$BUCKET_NAME" ] || [ "$BUCKET_NAME" = "null" ]; then
                echo "::error::Bucket name missing in ${folder}manifest.json. Skipping.";
                continue;
            fi
            folder_name=${folder%/}  # Remove trailing slash for cleaner output
            
            echo "📦 Deploying ${folder_name} to bucket: $BUCKET_NAME"
            
            if [ "$folder" = "central/" ]; then
              echo "  └── Uploading all central resources..."
              rclone copy "$folder" "r2-deploy:${BUCKET_NAME}/central" --exclude "manifest.json" -v
            elif [ -f "${folder}index.html" ]; then
              echo "  └── Uploading index.html..."
              rclone copy "${folder}index.html" "r2-deploy:${BUCKET_NAME}" -v
            else
              echo "  └── Skipping index.html (not found)"
            fi
            echo "  ✅ ${folder_name} deployment complete"
            echo ""
          else
            folder_name=${folder%/}
            echo "⏭️  Skipping ${folder_name} (no manifest.json file found)"
          fi
        done
        
        echo "🎉 All bucket deployments complete!" 